name: Actions Workflow

on: [push]

jobs:
   run-github-actions:
     runs-on: ubuntu-latest
     steps:
       - name: List Files
         run: |
          pwd
          ls -a
       - name: Checkout
         uses:actions/checkout@v1.git
       - name: Simple JS Actions
         id: greet
         uses: actions/https://github.com/actions/hello-world-javascript-action@v1.git
         with:
            who-to-greet: Aaron
       - name: Log Greeting Time
         run: echo 
          "${{ steps.greet.outputs.time }}"