name: shell commands

on: [push]

jobs:
  run-shell-command:
    run-on: ubuntu-latest
    steps:
      - name: echo a string
        run:  echo "Hello World"
      - name: multiline script 
        run: |
           node -v 
           npm -v  

      - name: python command
        run: |
          import platform
          print(platform.procesor())
        shell: python